[package]
name = "bitmice"
version = "1.0.0"
edition = "2021"
authors = ["AndrielFR <andrielfr@proton.me>"]
license = "BSD 3-Clause"
repository = "https://github.com/AndrielFR/bitmice"

[[bin]]
name = "bitmice"
path = "src/main.rs"

[dependencies]
bitmice-utils = { path = "../../lib/bitmice-utils" }
log = "0.4"
tokio = { version = "1.21.2", features = ["macros", "net", "rt-multi-thread", "sync", "io-util"] }
